### ISSUE TITLE
Account for SVG viewport

### ISSUE THREAD

**Issue by simensta** [zooniverse/modal-form#17]
When an SVG element is partially outside the viewport, the pointer and form should center on the visible portion of the element. I will start working on a solution (for some reason I can't assign the issue to myself).
<img width="300" alt="svg-element-out-of-viewport" src="https://cloud.githubusercontent.com/assets/7684729/14678157/424de6ac-06da-11e6-9173-4cf612c5927b.png">

**Comment by brian-c** [comment]
Ideally we'd make this work with any clipped element, SVG or not. Not quite sure how to do that. Maybe walk up the parents looking for `overflow: hidden` and set up some limits based on that?
